@base_url = http://localhost:3000

# @name login
POST {{base_url}}/auth/login
content-type: application/json

{
	"email": "jao@hcode.com.br",
	"password": "123456"
}

###

@authToken = {{login.response.body.accessToken}}

### Requests Find All
GET {{base_url}}/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Requests Find One
GET {{base_url}}/users/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Requests Create
POST {{base_url}}/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"name": "João Rangel II",
	"email": "jao2@hcode.com.br",
	"password": "123456"
}

### Requests Update
PUT  {{base_url}}/users/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"name": "João Rangel",
	"email": "joao@hcode.com.br",
	"password": "123456"
}

### Requests Update Partial
PATCH {{base_url}}/users/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	
	"birthAt": "1989-09-11"
}

### Requests Delete
DELETE  {{base_url}}/users/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
